name: Build and Push Docker Image on dockerhub but on different vm

on:
  push:
   branches:
      - main 
  

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        run: |
         docker build -t test:${{ github.sha }} .
         docker tag test:${{ github.sha }} test:latest

      - name: Save image
        run: |
         docker save test:${{ github.sha }} -o image.tar
      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

      - name: Show Artifact URL in Summary
        run: |
          echo "## Artifact Download URL" >> $GITHUB_STEP_SUMMARY
          echo "Artifact download URL: ${{ steps.upload_artifact.outputs.artifact-url }}" >> $GITHUB_STEP_SUMMARY


  push-image:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: |
          docker load -i image.tar

      - name: Tag image for DockerHub
        run: |
         docker tag test:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.sha }}
         docker tag test:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image
        run: |
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.sha }}
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
  deploy:
    runs-on: ubuntu-latest
    needs: push-image

    steps:

      - name: Deploy on Lightsail VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |

            echo "Login to DockerHub"
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

            echo "Pull latest image"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ github.sha }}
            echo "Restart container using docker compose"
            docker-compose down || true
            docker-compose up -d